### ISSUE TITLE
咋用

### ISSUE THREAD

**Issue by wy19901227** [SeanXiao1988/iOS-ZombieDetector#1]

**Comment by SeanXiao1988** [comment]
bool zombie_isZombie(id __unsafe_unretained targetObj, Class __unsafe_unretained targetCls)

**Comment by SeanXiao1988** [comment]
targetObj -> target id pointer
targetCls -> detected Class pointer
NSString *str = @"111";
bool zombie_isZombie(str, [NSString class]);
